services:
  mysql:
    image: mysql:8.2
    container_name: batch-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "33063:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
